language: node_js
node_js:
  - 10 # long term support
  - 11 # latest
os:
  - linux
  - osx
  - windows
matrix:
  fast_finish: true
  allow_failures:
    - os: windows # don't fail on timeout
install:
  - npm ci
  - npm run bootstrap
script:
  - npm run lint
  - npm test
  - npx lerna run build
  - npm run ci:commitlint # sometimes, it's OK for the commits to not be formatted correctly.  Make sure everything else runs
cache:
  directories:
    - ~/.npm
